import type { ModelInfo } from './types';

export const CHAT_MODEL_REGISTRY: ModelInfo[] = [
  {
    id: 'claude-opus-4-8',
    name: 'Claude Opus 4.8',
    platform: 'claude',
    input_price: 5,
    output_price: 25,
    context_window: 1000000,
    max_output_tokens: 128000,
    capabilities: ['chat', 'reasoning'],
  },
  {
    id: 'claude-sonnet-4-5-20250929',
    name: 'Claude Sonnet 4.5',
    platform: 'claude',
    input_price: 3,
    output_price: 15,
    context_window: 200000,
    max_output_tokens: 64000,
    capabilities: ['chat', 'reasoning'],
  },
  {
    id: 'claude-haiku-4-5-20251001',
    name: 'Claude Haiku 4.5',
    platform: 'claude',
    input_price: 1,
    output_price: 5,
    context_window: 200000,
    max_output_tokens: 64000,
    capabilities: ['chat'],
  },
  {
    id: 'gpt-5.5',
    name: 'GPT 5.5',
    platform: 'openai',
    input_price: 5,
    output_price: 30,
    context_window: 400000,
    max_output_tokens: 128000,
    capabilities: ['chat', 'reasoning'],
  },
  {
    id: 'gpt-5.4',
    name: 'GPT 5.4',
    platform: 'openai',
    input_price: 2.5,
    output_price: 15,
    context_window: 272000,
    max_output_tokens: 128000,
    capabilities: ['chat', 'reasoning'],
  },
  {
    id: 'gpt-5.4-mini',
    name: 'GPT 5.4 Mini',
    platform: 'openai',
    input_price: 0.75,
    output_price: 4.5,
    context_window: 128000,
    max_output_tokens: 128000,
    capabilities: ['chat', 'reasoning'],
  },
  {
    id: 'gemini-3-flash-preview',
    name: 'Gemini 3 Flash Preview',
    platform: 'gemini',
    input_price: 0.5,
    output_price: 3,
    context_window: 1000000,
    max_output_tokens: 65536,
    capabilities: ['chat'],
  },
  {
    id: 'gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro Preview',
    platform: 'gemini',
    input_price: 2,
    output_price: 12,
    context_window: 1000000,
    max_output_tokens: 65536,
    capabilities: ['chat'],
  },
  {
    id: 'gemini-3.5-flash',
    name: 'Gemini 3.5 Flash',
    platform: 'gemini',
    input_price: 1.5,
    output_price: 9,
    context_window: 1000000,
    max_output_tokens: 65536,
    capabilities: ['chat'],
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    platform: 'gemini',
    input_price: 0.3,
    output_price: 2.5,
    context_window: 1000000,
    max_output_tokens: 65536,
    capabilities: ['chat'],
  },
];
