import type { CSSProperties } from 'react';
import { cssVar } from '@doudou-start/airgate-theme';

export const keyframes = `
@keyframes pg-pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.3; }
}
@keyframes pg-fadein {
  from { opacity: 0; transform: translateY(6px); }
  to { opacity: 1; transform: translateY(0); }
}
@keyframes pg-spin {
  to { transform: rotate(360deg); }
}

/* ── Quiet Modern aesthetic ──
   单一字体（系统 Chinese ladder + 现代 sans for Latin），多权重撑层级，
   完全跟随 SDK 主题色系。没有任何复古/编辑级装饰。 */
[data-pg-aesthetic] {
  font-feature-settings: 'cv11' on, 'ss01' on;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility;
}

/* Canvas zoom button hover */
.pg-canvas-card { cursor: default; }
/* Canvas gallery card: hover 显示操作按钮 */
.pg-canvas-card:hover .pg-canvas-actions,
.pg-canvas-card:focus-within .pg-canvas-actions {
  opacity: 1;
}
.pg-canvas-card:hover {
  border-color: var(--ag-color-border, #d1d5db);
}

/* 删除按钮：hover 才显出，颜色保持中性，hover 时才染 danger */
.pg-conv-delete {
  opacity: 0;
  color: var(--ag-color-textTertiary, #9ca3af);
  transition: opacity 120ms ease, background 120ms ease, color 120ms ease;
}
.pg-conv-item:hover .pg-conv-delete,
.pg-conv-item:focus-within .pg-conv-delete {
  opacity: 1;
}
.pg-conv-delete:hover {
  background: var(--ag-color-dangerSubtle, rgba(239, 68, 68, 0.12));
  color: var(--ag-color-danger, #ef4444);
}
.pg-conv-delete:focus-visible {
  opacity: 1;
  outline: 2px solid var(--ag-color-borderFocus, #3b82f6);
  outline-offset: 1px;
}

.pg-conv-item {
  position: relative;
}
`;

export const styles: Record<string, CSSProperties> = {
  layout: {
    display: 'flex',
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    position: 'relative',
    isolation: 'isolate',
    background: cssVar('bgDeep'),
    fontFamily: cssVar('fontSans'),
    color: cssVar('text'),
    overflow: 'hidden',
  },
  studioLoading: {
    display: 'flex',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    background: cssVar('bgDeep'),
    color: cssVar('textSecondary'),
    fontFamily: cssVar('fontSans'),
    fontSize: 13,
  },

  // ── Sidebar ──
  sidebar: {
    width: 280,
    minWidth: 280,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    background: cssVar('bg'),
    borderRight: `1px solid ${cssVar('borderSubtle')}`,
    position: 'relative',
    zIndex: 3,
  },
  sidebarRail: {
    width: 48,
    minWidth: 48,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingTop: 12,
    background: cssVar('bg'),
    borderRight: `1px solid ${cssVar('borderSubtle')}`,
    flexShrink: 0,
    zIndex: 3,
  },
  sidebarRailMobile: {
    position: 'absolute',
    top: 0,
    left: 0,
    background: 'transparent',
    borderRight: 'none',
    zIndex: 4,
  },
  sidebarBackdrop: {
    position: 'absolute',
    inset: 0,
    background: 'rgba(6, 10, 18, 0.64)',
    zIndex: 2,
  },
  sidebarMobile: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 'min(84vw, 320px)',
    minWidth: 'min(84vw, 320px)',
    boxShadow: '0 18px 48px rgba(0, 0, 0, 0.32)',
  },
  sidebarHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    padding: '20px 12px 14px 8px',
  },
  sidebarTitleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minWidth: 0,
  },
  sidebarTitle: {
    fontSize: 13,
    fontWeight: 500,
    color: cssVar('text'),
    letterSpacing: '-0.005em',
  },
  newBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    border: 'none',
    borderRadius: 8,
    background: 'transparent',
    color: cssVar('textSecondary'),
    cursor: 'pointer',
    transition: cssVar('transition'),
    flexShrink: 0,
  },
  convList: {
    flex: 1,
    overflowY: 'auto',
    padding: '2px 8px 8px',
  },
  convItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 10px',
    borderRadius: 8,
    cursor: 'pointer',
    transition: cssVar('transition'),
    marginBottom: 1,
  },
  convTitle: {
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: 13,
    lineHeight: '18px',
    letterSpacing: '-0.003em',
  },
  deleteBtn: {
    width: 22,
    height: 22,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    border: 'none',
    borderRadius: 6,
    cursor: 'pointer',
    padding: 0,
    lineHeight: 1,
    flexShrink: 0,
    marginTop: 0,
  },
  emptyConvList: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
    padding: '32px 16px',
    color: cssVar('textTertiary'),
    fontSize: 12,
  },
  modeSwitcher: {
    display: 'flex',
    margin: '0 12px 8px',
    padding: 2,
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: cssVar('radiusSm'),
    background: cssVar('bgDeep'),
    gap: 2,
  },
  modeSwitcherItem: {
    flex: 1,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    padding: '6px 8px',
    border: 'none',
    borderRadius: 4,
    background: 'transparent',
    color: cssVar('textSecondary'),
    cursor: 'pointer',
    fontSize: 12,
    fontFamily: 'inherit',
    transition: cssVar('transition'),
  },
  modeSwitcherItemActive: {
    background: cssVar('bg'),
    color: cssVar('text'),
    fontWeight: 500,
  },
  balanceBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    padding: '14px 16px 18px',
  },
  balanceLabel: {
    fontSize: 11,
    fontWeight: 500,
    color: cssVar('textTertiary'),
    letterSpacing: '0.02em',
  },
  balanceValue: {
    fontSize: 13,
    fontWeight: 500,
    color: cssVar('text'),
    fontVariantNumeric: 'tabular-nums',
  },

  // ── Main ──
  main: {
    position: 'relative' as const,
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
  },

  toggleBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    border: 'none',
    borderRadius: cssVar('radiusSm'),
    background: 'transparent',
    color: cssVar('textSecondary'),
    cursor: 'pointer',
    transition: cssVar('transition'),
    flexShrink: 0,
  },
  // 模型/尺寸/Effort 选择器现在嵌在输入卡片内（左侧），跟附件 / 图片 / 发送按钮
  // 同一行。所以 chip 走透明底，避免在 bgSurface 卡片上再叠一层 surface 制造
  // "卡上有卡"的层级噪声。
  selectors: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
    minWidth: 0,
    flex: 1,
  },
  selectorsMobile: {
    width: '100%',
    gap: 4,
    rowGap: 2,
  },
  selectWrap: {
    position: 'relative',
    minWidth: 0,
  },
  modelSelectWrap: {
    flex: '0 1 280px',
  },
  selectTrigger: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
    width: '100%',
    border: 'none',
    borderRadius: 8,
    background: 'transparent',
    color: cssVar('textSecondary'),
    fontFamily: cssVar('fontSans'),
    fontWeight: 500,
    outline: 'none',
    cursor: 'pointer',
    transition: cssVar('transition'),
  },
  selectTriggerOpen: {
    background: cssVar('bgHover'),
    color: cssVar('text'),
  },
  selectTriggerText: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  selectTriggerCaret: {
    flexShrink: 0,
    color: cssVar('textTertiary'),
    fontSize: 10,
    lineHeight: 1,
  },
  modelSelectTrigger: {
    maxWidth: 280,
    padding: '4px 8px',
    color: cssVar('text'),
    fontSize: 13,
    letterSpacing: '-0.003em',
  },
  modelSelectTriggerMobile: {
    maxWidth: '100%',
    padding: '3px 6px',
    fontSize: 12,
  },
  chipSelectTrigger: {
    height: 26,
    padding: '2px 8px',
    fontSize: 12,
  },
  chipSelectTriggerMobile: {
    height: 24,
    padding: '1px 6px',
    fontSize: 11,
  },
  selectPopover: {
    position: 'absolute',
    left: 0,
    bottom: 'calc(100% + 8px)',
    zIndex: 20,
    display: 'flex',
    flexDirection: 'column',
    minWidth: '100%',
    maxHeight: 320,
    padding: 6,
    border: `1px solid ${cssVar('border')}`,
    borderRadius: cssVar('radiusSm'),
    background: cssVar('bg'),
    boxShadow: '0 20px 54px rgba(0, 0, 0, 0.34)',
    overflowY: 'auto',
  },
  selectPopoverModel: {
    width: 390,
    maxWidth: 'calc(100vw - 32px)',
  },
  selectPopoverChip: {
    width: 'max-content',
    minWidth: 116,
  },
  selectOverlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 1000,
    display: 'flex',
    alignItems: 'flex-end',
    padding: 10,
    background: 'rgba(4, 7, 13, 0.62)',
  },
  selectSheet: {
    width: '100%',
    maxHeight: '72vh',
    padding: 8,
    border: `1px solid ${cssVar('border')}`,
    borderRadius: '18px 18px 14px 14px',
    background: cssVar('bg'),
    boxShadow: '0 -18px 60px rgba(0, 0, 0, 0.38)',
    overflow: 'hidden',
  },
  selectSheetHeader: {
    padding: '5px 8px 10px',
    color: cssVar('textTertiary'),
    fontSize: 11,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  selectPopoverMobile: {
    position: 'relative',
    left: 'auto',
    bottom: 'auto',
    zIndex: 'auto',
    width: '100%',
    minWidth: '100%',
    maxWidth: 'none',
    maxHeight: 'calc(72vh - 48px)',
    padding: 0,
    border: 'none',
    borderRadius: 0,
    background: 'transparent',
    boxShadow: 'none',
  },
  selectOption: {
    display: 'block',
    width: '100%',
    padding: '8px 10px',
    border: 'none',
    borderRadius: 8,
    background: 'transparent',
    color: cssVar('textSecondary'),
    fontFamily: cssVar('fontSans'),
    fontSize: 12,
    fontWeight: 500,
    lineHeight: 1.35,
    textAlign: 'left',
    whiteSpace: 'nowrap',
    cursor: 'pointer',
  },
  selectOptionModel: {
    fontSize: 13,
  },
  selectOptionActive: {
    background: cssVar('primarySubtle'),
    color: cssVar('primary'),
  },
  imageSizeInlineControls: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
  },
  imageSizeInlineControlsMobile: {
    flex: '0 1 auto',
    flexWrap: 'wrap',
    gap: 4,
  },
  imageSizeInlinePreview: {
    padding: '3px 9px',
    color: cssVar('textTertiary'),
    fontSize: 12,
    fontFamily: cssVar('fontMono'),
    whiteSpace: 'nowrap',
  },

  // ── Messages ──
  messagesArea: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
  },

  // ── Empty state ──
  // 居中、克制、靠层级与留白说话。一个标题、一个描述、一个 primary CTA。
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    gap: 14,
    padding: '40px 32px',
    maxWidth: 480,
    margin: '0 auto',
    width: '100%',
    textAlign: 'center',
    animation: 'pg-fadein 0.4s ease-out',
  },
  emptyStateMobile: {
    padding: '32px 24px',
    gap: 12,
  },
  emptyTitle: {
    fontSize: 32,
    fontWeight: 500,
    color: cssVar('text'),
    lineHeight: 1.18,
    letterSpacing: '-0.018em',
    margin: 0,
  },
  emptyDesc: {
    fontSize: 14,
    color: cssVar('textTertiary'),
    lineHeight: 1.55,
    margin: 0,
  },
  emptyBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '10px 20px',
    border: 'none',
    borderRadius: 999,
    background: cssVar('primary'),
    color: cssVar('textInverse'),
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
    transition: cssVar('transition'),
    marginTop: 12,
  },

  // ── Message row ──
  // ChatGPT 风格：用户消息右对齐圆角气泡（bgSurface），助手消息左对齐无气泡纯
  // 排版。两侧都不显示 avatar 和"你/助手"role label。借助 padding 拉空气，
  // 取消行间分割线。整列居中、限定 768px 宽，营造窄列阅读体验。
  messageRow: {
    display: 'flex',
    width: '100%',
    maxWidth: 768,
    margin: '0 auto',
    padding: '14px 24px',
    animation: 'pg-fadein 0.25s ease-out',
  },
  messageRowMobile: {
    padding: '10px 14px',
  },
  messageRowUser: {
    justifyContent: 'flex-end',
  },
  messageRowAssistant: {
    justifyContent: 'flex-start',
  },
  userBubble: {
    maxWidth: '78%',
    minWidth: 0,
    padding: '11px 16px',
    borderRadius: 18,
    background: cssVar('bgSurface'),
    border: `1px solid ${cssVar('borderSubtle')}`,
  },
  userBubbleMobile: {
    maxWidth: '82%',
    padding: '10px 13px',
    borderRadius: 16,
  },
  assistantBlock: {
    maxWidth: '100%',
    width: '100%',
    minWidth: 0,
  },
  messageCopyBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 24,
    height: 24,
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: '999px',
    background: 'transparent',
    color: cssVar('textTertiary'),
    cursor: 'pointer',
    transition: cssVar('transition'),
  },
  messageCopyAfterText: {
    display: 'inline-flex',
    verticalAlign: 'text-bottom',
    marginLeft: 6,
    opacity: 0,
    pointerEvents: 'none',
    transform: 'translateY(1px)',
    transition: cssVar('transition'),
  },
  messageCopyAfterTextVisible: {
    opacity: 1,
    pointerEvents: 'auto',
  },
  messageCopyAfterTextBtn: {
    width: 22,
    height: 22,
  },
  messageContent: {
    fontSize: 14,
    lineHeight: 1.72,
    wordBreak: 'break-word',
    color: cssVar('text'),
  },
  markdownParagraph: {
    margin: '0 0 11px',
  },
  markdownH1: {
    margin: '4px 0 14px',
    fontSize: 22,
    fontWeight: 600,
    lineHeight: 1.25,
    letterSpacing: '-0.015em',
    color: cssVar('text'),
  },
  markdownH2: {
    margin: '18px 0 10px',
    fontSize: 18,
    fontWeight: 600,
    lineHeight: 1.3,
    letterSpacing: '-0.01em',
    color: cssVar('text'),
  },
  markdownH3: {
    margin: '16px 0 8px',
    fontSize: 15,
    fontWeight: 600,
    lineHeight: 1.35,
    color: cssVar('text'),
  },
  markdownH4: {
    margin: '14px 0 8px',
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.4,
    color: cssVar('text'),
  },
  markdownList: {
    margin: '0 0 12px',
    paddingLeft: 20,
    color: cssVar('text'),
  },
  markdownListItem: {
    margin: '4px 0',
  },
  markdownBlockquote: {
    margin: '0 0 12px',
    padding: '9px 13px',
    borderLeft: `3px solid ${cssVar('primary')}`,
    borderRadius: '0 10px 10px 0',
    background: cssVar('primarySubtle'),
    color: cssVar('textSecondary'),
  },
  markdownCodeBlock: {
    margin: '4px 0 14px',
    padding: '13px 15px',
    borderRadius: cssVar('radiusSm'),
    background: cssVar('bgDeep'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    color: cssVar('text'),
    fontFamily: cssVar('fontMono'),
    fontSize: 12.5,
    lineHeight: 1.72,
    overflowX: 'auto',
    whiteSpace: 'pre',
  },
  markdownInlineCode: {
    padding: '1px 5px 2px',
    borderRadius: 6,
    background: cssVar('bgSurface'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    color: cssVar('primary'),
    fontFamily: cssVar('fontMono'),
    fontSize: '0.9em',
  },
  markdownInlineMath: {
    display: 'inline-block',
    maxWidth: '100%',
    overflowX: 'auto',
    overflowY: 'hidden',
    verticalAlign: '-0.18em',
  },
  markdownBlockMath: {
    margin: '4px 0 14px',
    padding: '12px 14px',
    borderRadius: cssVar('radiusSm'),
    background: cssVar('bgSurface'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    color: cssVar('text'),
    overflowX: 'auto',
    overflowY: 'hidden',
  },
  markdownLink: {
    color: cssVar('primary'),
    textDecoration: 'underline',
    textDecorationColor: cssVar('primary'),
    textUnderlineOffset: 3,
  },
  markdownDivider: {
    height: 1,
    border: 0,
    background: cssVar('border'),
    margin: '16px 0',
  },
  reasoningBox: {
    marginBottom: 10,
    padding: '10px 12px',
    borderRadius: cssVar('radiusSm'),
    background: cssVar('bgSurface'),
    border: `1px solid ${cssVar('borderSubtle')}`,
  },
  reasoningSummary: {
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 12,
    fontWeight: 600,
    color: cssVar('textSecondary'),
    userSelect: 'none',
  },
  reasoningContent: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 1.6,
    wordBreak: 'break-word',
    color: cssVar('textSecondary'),
  },
  imageGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    gap: 12,
    maxWidth: '100%',
    margin: '10px 0 6px',
  },
  imageGroupMobile: {
    gap: 8,
    marginTop: 8,
  },
  generatedImageFrame: {
    position: 'relative',
    display: 'inline-flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 8,
    flex: '1 1 180px',
    maxWidth: 'min(100%, 320px)',
    minWidth: 0,
  },
  generatedImageFrameMobile: {
    flex: '1 1 140px',
    maxWidth: 'min(100%, 240px)',
  },
  generatedImagePreviewBtn: {
    display: 'block',
    width: '100%',
    padding: 0,
    border: 'none',
    background: 'transparent',
    cursor: 'zoom-in',
    textAlign: 'left',
    font: 'inherit',
  },
  generatedImageActions: {
    position: 'absolute',
    left: 8,
    bottom: 8,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: 4,
    borderRadius: '999px',
    border: `1px solid ${cssVar('glassBorder')}`,
    background: cssVar('glass'),
    color: cssVar('text'),
    backdropFilter: 'blur(10px)',
    boxShadow: cssVar('shadowMd'),
  },
  generatedImageDimensions: {
    display: 'block',
    marginTop: 4,
    fontSize: 11,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    color: cssVar('textTertiary'),
    textAlign: 'center' as const,
  },
  generatedImageOverlayWrap: {
    position: 'relative',
    display: 'block',
    width: '100%',
    borderRadius: cssVar('radiusMd'),
    overflow: 'hidden',
  },
  generatedImage: {
    display: 'block',
    maxHeight: 420,
    width: '100%',
    height: 'auto',
    borderRadius: cssVar('radiusMd'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    objectFit: 'contain',
  },
  generatedImageDimOverlay: {
    position: 'absolute',
    inset: 0,
    borderRadius: cssVar('radiusMd'),
    background: 'rgba(15, 23, 42, 0.34)',
    pointerEvents: 'none',
  },
  generatedImageSelection: {
    position: 'absolute',
    border: `2px solid ${cssVar('primary')}`,
    background: 'rgba(45, 212, 191, 0.2)',
    boxShadow: '0 0 0 9999px rgba(3, 7, 18, 0.18), 0 0 18px rgba(45, 212, 191, 0.35)',
    pointerEvents: 'none',
  },
  imageDownloadBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    padding: 0,
    borderRadius: '999px',
    border: `1px solid ${cssVar('borderSubtle')}`,
    background: cssVar('bgSurface'),
    color: 'inherit',
    cursor: 'pointer',
    transition: cssVar('transition'),
  },
  regenerateImageBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    padding: 0,
    borderRadius: '999px',
    border: `1px solid ${cssVar('borderSubtle')}`,
    background: cssVar('bgSurface'),
    color: 'inherit',
    cursor: 'pointer',
    transition: cssVar('transition'),
  },
  imageRetrySpinner: {
    width: 14,
    height: 14,
    borderRadius: '999px',
    border: '2px solid currentColor',
    borderTopColor: 'transparent',
    animation: 'pg-spin 0.75s linear infinite',
  },
  imagePreviewOverlay: {
    position: 'absolute',
    inset: 0,
    zIndex: 100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    background: 'rgba(4, 7, 13, 0.78)',
    backdropFilter: 'blur(10px)',
  },
  imagePreviewModal: {
    position: 'relative',
    display: 'flex',
    maxWidth: 'min(94vw, 1120px)',
    maxHeight: '90vh',
    width: 'fit-content',
    borderRadius: cssVar('radiusLg'),
    border: `1px solid ${cssVar('border')}`,
    background: cssVar('bgDeep'),
    boxShadow: '0 28px 90px rgba(0, 0, 0, 0.45)',
    overflow: 'hidden',
  },
  imagePreviewNavBtn: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 42,
    height: 42,
    border: `1px solid ${cssVar('glassBorder')}`,
    borderRadius: '999px',
    background: cssVar('glass'),
    color: cssVar('text'),
    fontSize: 34,
    lineHeight: 1,
    cursor: 'pointer',
    backdropFilter: 'blur(10px)',
    boxShadow: cssVar('shadowMd'),
  },
  imagePreviewCounter: {
    position: 'absolute',
    left: '50%',
    bottom: 12,
    transform: 'translateX(-50%)',
    padding: '5px 10px',
    borderRadius: '999px',
    border: `1px solid ${cssVar('glassBorder')}`,
    background: cssVar('glass'),
    color: cssVar('textSecondary'),
    fontSize: 12,
    backdropFilter: 'blur(10px)',
    boxShadow: cssVar('shadowMd'),
  },
  imagePreviewCloseBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    border: `1px solid ${cssVar('glassBorder')}`,
    borderRadius: '999px',
    background: cssVar('glass'),
    color: cssVar('text'),
    fontSize: 22,
    lineHeight: 1,
    cursor: 'pointer',
    backdropFilter: 'blur(10px)',
    boxShadow: cssVar('shadowMd'),
  },
  imagePreviewLarge: {
    display: 'block',
    maxWidth: 'min(94vw, 1120px)',
    maxHeight: '90vh',
    width: 'auto',
    height: 'auto',
    objectFit: 'contain',
    background: cssVar('bgDeep'),
  },
  interactionNotice: {
    position: 'sticky',
    bottom: 12,
    alignSelf: 'center',
    zIndex: 4,
    padding: '7px 12px',
    borderRadius: '999px',
    background: cssVar('bgElevated'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    color: cssVar('textSecondary'),
    fontSize: 12,
    boxShadow: cssVar('shadowMd'),
  },
  canvasInteractionNotice: {
    position: 'absolute' as const,
    top: 60,
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 30,
    padding: '8px 16px',
    borderRadius: '999px',
    background: cssVar('bgElevated'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    color: cssVar('textSecondary'),
    fontSize: 12,
    fontWeight: 600,
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.3)',
    backdropFilter: 'blur(10px)',
    animation: 'pg-fadein 0.15s ease-out',
    pointerEvents: 'none' as const,
    whiteSpace: 'nowrap' as const,
  },
  messageMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    fontSize: 11,
    color: cssVar('textTertiary'),
  },
  metaBadge: {
    display: 'inline-flex',
    padding: '2px 8px',
    borderRadius: '999px',
    background: cssVar('bgSurface'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    fontSize: 11,
    fontFamily: cssVar('fontMono'),
    color: cssVar('textSecondary'),
  },
  streamingDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: cssVar('primary'),
    animation: 'pg-pulse 1.2s ease-in-out infinite',
  },
  thinkingDots: {
    animation: 'pg-pulse 1.5s ease-in-out infinite',
  },

  // ── Error ──
  errorBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    margin: '8px 28px',
    padding: '10px 14px',
    borderRadius: cssVar('radiusSm'),
    background: cssVar('dangerSubtle'),
    color: cssVar('danger'),
    fontSize: 13,
    border: `1px solid ${cssVar('danger')}`,
    borderColor: 'rgba(251, 113, 133, 0.2)',
  },
  errorBarMobile: {
    margin: '8px 14px',
  },
  errorMessage: {
    flex: 1,
    minWidth: 0,
  },
  recoverableBar: {
    background: cssVar('primarySubtle'),
    color: cssVar('primary'),
    borderColor: 'rgba(45, 212, 191, 0.22)',
  },
  errorRetryBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '5px 10px',
    borderRadius: '999px',
    border: '1px solid rgba(251, 113, 133, 0.28)',
    background: 'rgba(251, 113, 133, 0.1)',
    color: cssVar('danger'),
    fontSize: 12,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: cssVar('fontSans'),
  },
  recoverableRetryBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '5px 10px',
    borderRadius: '999px',
    border: '1px solid rgba(45, 212, 191, 0.3)',
    background: 'rgba(45, 212, 191, 0.12)',
    color: cssVar('primary'),
    fontSize: 12,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: cssVar('fontSans'),
  },

  // ── Input ──
  inputArea: {
    padding: '12px 28px 20px',
    background: 'transparent',
    flexShrink: 0,
  },
  inputAreaMobile: {
    padding: '8px 10px 10px',
  },
  inputWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    border: `1px solid ${cssVar('border')}`,
    borderRadius: 22,
    background: cssVar('bgSurface'),
    paddingTop: 10,
    paddingRight: 12,
    paddingBottom: 8,
    paddingLeft: 12,
    transition: cssVar('transition'),
    width: '100%',
    maxWidth: 768,
    margin: '0 auto',
  },
  inputWrapperMobile: {
    gap: 7,
    borderRadius: 20,
    paddingTop: 9,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
  },
  inputWrapperStreaming: {
    paddingTop: 8,
    paddingBottom: 8,
  },
  imageEditPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    padding: 12,
    borderRadius: cssVar('radiusMd'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    background: cssVar('bgSurface'),
  },
  imageEditPanelMobile: {
    padding: 10,
  },
  imageEditHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  imageEditHeaderMobile: {
    flexDirection: 'column',
  },
  imageEditTitleWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    minWidth: 0,
  },
  imageEditTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: cssVar('text'),
  },
  imageEditSubtitle: {
    fontSize: 12,
    color: cssVar('textTertiary'),
  },
  imageEditHeaderActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  imageEditGhostBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 30,
    padding: '6px 10px',
    borderRadius: cssVar('radiusSm'),
    border: `1px solid ${cssVar('border')}`,
    background: cssVar('bgElevated'),
    color: cssVar('textSecondary'),
    fontSize: 12,
    fontWeight: 700,
    cursor: 'pointer',
    transition: cssVar('transition'),
    fontFamily: cssVar('fontSans'),
  },
  imageEditIconBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
    borderRadius: '999px',
    border: `1px solid ${cssVar('borderSubtle')}`,
    background: cssVar('bgElevated'),
    color: cssVar('textSecondary'),
    fontSize: 18,
    lineHeight: 1,
    cursor: 'pointer',
  },
  imageEditBody: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 150px',
    gap: 12,
    alignItems: 'stretch',
  },
  imageEditBodyMobile: {
    gridTemplateColumns: '1fr',
  },
  imageEditStageWrap: {
    minWidth: 0,
    overflow: 'auto',
    borderRadius: cssVar('radiusMd'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    background: cssVar('bgDeep'),
    padding: 8,
  },
  imageEditStage: {
    position: 'relative',
    display: 'inline-flex',
    maxWidth: '100%',
    borderRadius: cssVar('radiusSm'),
    overflow: 'hidden',
    verticalAlign: 'top',
  },
  imageEditSource: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    userSelect: 'none',
  },
  imageEditCanvas: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    touchAction: 'none',
    cursor: 'crosshair',
  },
  imageEditSelection: {
    position: 'absolute',
    zIndex: 1,
    border: '2px solid rgba(45, 212, 191, 0.95)',
    background: 'rgba(45, 212, 191, 0.2)',
    boxShadow: '0 0 0 9999px rgba(2, 6, 14, 0.28), 0 0 18px rgba(45, 212, 191, 0.35)',
    pointerEvents: 'none',
  },
  imageEditSidePanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    justifyContent: 'space-between',
    minWidth: 0,
    padding: 10,
    borderRadius: cssVar('radiusSm'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    background: cssVar('bgSurface'),
  },
  imageEditBadge: {
    display: 'inline-flex',
    width: 'fit-content',
    padding: '4px 8px',
    borderRadius: '999px',
    background: cssVar('primarySubtle'),
    color: cssVar('primary'),
    fontSize: 11,
    fontWeight: 800,
    fontFamily: cssVar('fontMono'),
  },
  imageEditFilename: {
    color: cssVar('textTertiary'),
    fontSize: 12,
    lineHeight: 1.4,
    wordBreak: 'break-word',
  },
  imageEditEmptyBtn: {
    minHeight: 96,
    borderRadius: cssVar('radiusMd'),
    border: `1px dashed ${cssVar('border')}`,
    background: 'rgba(45, 212, 191, 0.05)',
    color: cssVar('primary'),
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: cssVar('fontSans'),
  },
  editModalOverlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 50,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    background: 'rgba(4, 7, 13, 0.78)',
    backdropFilter: 'blur(10px)',
  },
  editModalCard: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    width: 'min(96vw, 1080px)',
    maxHeight: '92vh',
    padding: 18,
    borderRadius: cssVar('radiusLg'),
    border: `1px solid ${cssVar('border')}`,
    background: cssVar('bgDeep'),
    boxShadow: '0 28px 90px rgba(0, 0, 0, 0.45)',
    overflow: 'hidden',
  },
  editModalCardMobile: {
    width: '100%',
    maxHeight: '94vh',
    padding: 12,
    gap: 10,
  },
  editModalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  editModalBody: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 200px',
    gap: 14,
    minHeight: 0,
    flex: 1,
    alignItems: 'stretch',
  },
  editModalBodyMobile: {
    gridTemplateColumns: '1fr',
  },
  editModalStageWrap: {
    minWidth: 0,
    overflow: 'auto',
    borderRadius: cssVar('radiusMd'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    background: cssVar('bgDeep'),
    padding: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  editModalSide: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    padding: 12,
    borderRadius: cssVar('radiusSm'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    background: cssVar('bgSurface'),
  },
  editModalFooter: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  editModalPrompt: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '10px 12px',
    borderRadius: cssVar('radiusSm'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    background: cssVar('bgSurface'),
    color: cssVar('text'),
    fontFamily: cssVar('fontSans'),
    fontSize: 13,
    lineHeight: 1.5,
    resize: 'vertical',
    minHeight: 60,
    outline: 'none',
  },
  editModalActions: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  editModalHint: {
    fontSize: 11,
    color: cssVar('textTertiary'),
    flex: 1,
    minWidth: 0,
  },
  editModalBtnGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  editModalSubmitBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '9px 16px',
    border: 'none',
    borderRadius: cssVar('radiusSm'),
    background: cssVar('primary'),
    color: cssVar('textInverse'),
    fontSize: 13,
    fontWeight: 600,
    fontFamily: cssVar('fontSans'),
    cursor: 'pointer',
    transition: cssVar('transition'),
  },
  editModalStatus: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    borderRadius: cssVar('radiusSm'),
    background: cssVar('primarySubtle'),
    color: cssVar('primary'),
    fontSize: 12,
    fontWeight: 500,
  },
  editModalError: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    borderRadius: cssVar('radiusSm'),
    background: cssVar('dangerSubtle'),
    color: cssVar('danger'),
    fontSize: 12,
    fontWeight: 500,
  },
  imagePreviewList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  imagePreviewItem: {
    position: 'relative',
    width: 76,
    height: 76,
    padding: 0,
    borderRadius: cssVar('radiusSm'),
    overflow: 'hidden',
    border: `1px solid ${cssVar('borderSubtle')}`,
    background: cssVar('bgHover'),
    cursor: 'pointer',
  },
  imagePreviewItemActive: {
    borderColor: cssVar('primary'),
    boxShadow: `0 0 0 1px ${cssVar('primary')}`,
  },
  imagePreview: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  imagePreviewEditBadge: {
    position: 'absolute',
    left: 4,
    bottom: 4,
    padding: '2px 6px',
    borderRadius: 999,
    border: `1px solid ${cssVar('glassBorder')}`,
    background: cssVar('glass'),
    color: cssVar('text'),
    fontSize: 11,
    lineHeight: '14px',
    pointerEvents: 'none',
  },
  removeImageBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    border: `1px solid ${cssVar('glassBorder')}`,
    borderRadius: 999,
    background: cssVar('glass'),
    color: cssVar('text'),
    cursor: 'pointer',
    lineHeight: '20px',
    padding: 0,
    fontSize: 16,
  },
  textarea: {
    width: '100%',
    border: 'none',
    background: 'transparent',
    color: cssVar('text'),
    fontSize: 14,
    fontFamily: cssVar('fontSans'),
    resize: 'none',
    outline: 'none',
    lineHeight: 1.55,
    height: 24,
    minHeight: 24,
    maxHeight: 128,
  },
  inputActions: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  inputActionsMobile: {
    alignItems: 'stretch',
    flexDirection: 'column',
    gap: 7,
  },
  inputButtonGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  inputButtonGroupMobile: {
    width: '100%',
    minWidth: 0,
    justifyContent: 'space-between',
    gap: 6,
  },
  fileInput: {
    display: 'none',
  },
  inputHint: {
    fontSize: 11,
    color: cssVar('textTertiary'),
  },
  inputHintMobile: {
    display: 'none',
  },
  attachBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '7px 12px',
    border: 'none',
    borderRadius: 999,
    background: 'transparent',
    color: cssVar('textSecondary'),
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    transition: cssVar('transition'),
  },
  attachBtnActive: {
    background: cssVar('primarySubtle'),
    color: cssVar('primary'),
  },
  thinkingToggleBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '7px 12px',
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: 999,
    background: 'transparent',
    color: cssVar('textTertiary'),
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    transition: cssVar('transition'),
  },
  thinkingToggleBtnActive: {
    background: cssVar('primarySubtle'),
    borderColor: 'rgba(45, 212, 191, 0.28)',
    color: cssVar('primary'),
  },
  sendBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '7px 14px',
    border: 'none',
    borderRadius: 999,
    background: cssVar('primary'),
    color: cssVar('textInverse'),
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
    transition: cssVar('transition'),
  },
  stopBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '7px 14px',
    border: 'none',
    borderRadius: 999,
    background: cssVar('dangerSubtle'),
    color: cssVar('danger'),
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
  },
  actionBtnMobile: {
    flex: '0 1 auto',
    minWidth: 44,
    minHeight: 36,
    justifyContent: 'center',
    padding: '8px 11px',
  },

  // ── Canvas Mode ──
  mainCanvas: {
    position: 'relative' as const,
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
  },
  canvasViewToggle: {
    position: 'absolute' as const,
    top: 10,
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 20,
    display: 'flex',
    gap: 2,
    background: cssVar('bgDeep'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: 10,
    padding: 3,
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.2)',
  },
  canvasViewToggleCanvas: {
    left: 'calc(50% + 195px)',
  },
  canvasViewToggleMobile: {
    top: 6,
    left: '50%',
  },
  canvasViewToggleBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    padding: '6px 14px',
    border: `1px solid transparent`,
    borderRadius: 8,
    background: 'transparent',
    color: cssVar('textSecondary'),
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: cssVar('transition'),
  },
  canvasViewToggleBtnActive: {
    background: cssVar('bgSurface'),
    color: cssVar('text'),
    fontWeight: 600,
    borderColor: cssVar('borderSubtle'),
  },
  canvasLayout: {
    flex: 1,
    display: 'flex',
    minHeight: 0,
    gap: 0,
  },
  canvasLayoutMobile: {
    flexDirection: 'column' as const,
  },
  canvasPortfolio: {
    width: 390,
    minWidth: 340,
    maxWidth: 440,
    display: 'flex',
    flexDirection: 'column' as const,
    minHeight: 0,
    background: `linear-gradient(180deg, ${cssVar('bg')} 0%, ${cssVar('bgDeep')} 100%)`,
    borderRight: `1px solid ${cssVar('borderSubtle')}`,
    flexShrink: 0,
  },
  canvasPortfolioHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    padding: '18px 18px 12px',
    flexShrink: 0,
  },
  canvasPortfolioTitleWrap: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
    minWidth: 0,
  },
  canvasPortfolioTitle: {
    fontSize: 18,
    fontWeight: 800,
    color: cssVar('text'),
    letterSpacing: '-0.035em',
    lineHeight: 1.1,
  },
  canvasPortfolioNewBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: 9,
    background: cssVar('bgSurface'),
    color: cssVar('textSecondary'),
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: cssVar('transition'),
    flexShrink: 0,
  },
  canvasPortfolioProjects: {
    display: 'flex',
    gap: 6,
    overflowX: 'auto' as const,
    padding: '0 14px 10px',
    flexShrink: 0,
  },
  canvasPortfolioProject: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    minWidth: 96,
    maxWidth: 150,
    padding: '6px 8px',
    borderRadius: 10,
    border: `1px solid ${cssVar('borderSubtle')}`,
    background: 'transparent',
    color: cssVar('textSecondary'),
    cursor: 'pointer',
    transition: cssVar('transition'),
  },
  canvasPortfolioProjectActive: {
    background: cssVar('bgSurface'),
    color: cssVar('text'),
    borderColor: cssVar('border'),
  },
  canvasPortfolioProjectTitle: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: 12,
    fontWeight: 700,
  },
  canvasPortfolioStats: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '0 18px 14px',
    flexShrink: 0,
  },
  canvasPortfolioList: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '0 12px 18px',
  },
  canvasPortfolioItem: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    padding: '8px 8px',
    borderRadius: 6,
    cursor: 'pointer',
    transition: cssVar('transition'),
    position: 'relative' as const,
  },
  canvasPortfolioItemTitle: {
    fontSize: 13,
    lineHeight: '1.4',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    paddingRight: 20,
  },
  canvasPortfolioItemDate: {
    fontSize: 11,
    color: cssVar('textTertiary'),
  },
  canvasPortfolioEmpty: {
    padding: '20px 10px',
    fontSize: 12,
    color: cssVar('textTertiary'),
    textAlign: 'center' as const,
  },
  canvasGallery: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    position: 'relative' as const,
    borderRight: `1px solid ${cssVar('borderSubtle')}`,
    background: cssVar('bgDeep'),
    backgroundImage: `radial-gradient(circle, ${cssVar('borderSubtle')} 1px, transparent 1px)`,
    touchAction: 'none',
    userSelect: 'none' as const,
    WebkitUserSelect: 'none' as const,
  },
  canvasGalleryMobile: {
    flex: 1,
    borderRight: 'none',
    borderBottom: `1px solid ${cssVar('borderSubtle')}`,
  },
  canvasSpatial: {
    position: 'absolute' as const,
    top: '50%',
    left: '50%',
    transformOrigin: '0 0',
  },
  canvasZoomControls: {
    position: 'absolute' as const,
    bottom: 16,
    left: 16,
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    padding: '4px 6px',
    borderRadius: 8,
    background: 'rgba(0, 0, 0, 0.55)',
    backdropFilter: 'blur(10px)',
    color: '#fff',
    zIndex: 2,
  },
  canvasZoomBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    border: 'none',
    borderRadius: 6,
    background: 'transparent',
    color: 'inherit',
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'background 120ms ease',
  },
  canvasZoomLabel: {
    fontSize: 11,
    fontWeight: 500,
    fontVariantNumeric: 'tabular-nums',
    padding: '0 4px',
    minWidth: 36,
    textAlign: 'center' as const,
  },
  canvasGalleryCard: {
    position: 'relative' as const,
    background: cssVar('bgSurface'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: cssVar('radiusSm'),
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column' as const,
    transition: cssVar('transition'),
  },
  canvasGalleryThumb: {
    border: 'none',
    padding: 0,
    margin: 0,
    background: cssVar('bgDeep'),
    cursor: 'zoom-in',
    display: 'block',
    width: '100%',
    aspectRatio: '1 / 1',
    overflow: 'hidden',
    fontFamily: 'inherit',
  },
  canvasGalleryImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
    display: 'block',
    imageRendering: 'auto',
  },
  canvasGalleryFooter: {
    padding: '8px 10px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 3,
    minWidth: 0,
  },
  canvasGalleryPrompt: {
    fontSize: 12,
    color: cssVar('text'),
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  canvasGalleryMeta: {
    fontSize: 11,
    color: cssVar('textTertiary'),
    fontVariantNumeric: 'tabular-nums',
  },
  canvasGalleryActions: {
    position: 'absolute' as const,
    right: 8,
    top: 8,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '3px 4px',
    borderRadius: 8,
    background: 'rgba(0, 0, 0, 0.55)',
    color: '#fff',
    backdropFilter: 'blur(10px)',
    opacity: 0,
    transition: cssVar('transition'),
  },
  canvasGalleryEmpty: {
    position: 'absolute' as const,
    inset: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    padding: '40px 24px 160px',
    color: cssVar('textTertiary'),
    pointerEvents: 'none' as const,
  },
  canvasWorkflow: {
    width: 390,
    minWidth: 340,
    maxWidth: 440,
    display: 'flex',
    flexDirection: 'column' as const,
    minHeight: 0,
    background: `linear-gradient(180deg, ${cssVar('bg')} 0%, ${cssVar('bgDeep')} 100%)`,
    borderLeft: `1px solid ${cssVar('borderSubtle')}`,
    flexShrink: 0,
  },
  canvasWorkflowMobile: {
    width: '100%',
    minWidth: '100%',
    maxWidth: '100%',
    maxHeight: '44vh',
    borderLeft: 'none',
    borderTop: `1px solid ${cssVar('borderSubtle')}`,
  },
  canvasWorkflowHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    padding: '18px 18px 14px',
    borderBottom: `1px solid ${cssVar('borderSubtle')}`,
    flexShrink: 0,
  },
  canvasWorkflowHeaderCopy: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
    minWidth: 0,
  },
  canvasWorkflowEyebrow: {
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.14em',
    color: cssVar('primary'),
    fontFamily: cssVar('fontMono'),
  },
  canvasWorkflowHeaderTitle: {
    fontSize: 18,
    fontWeight: 800,
    color: cssVar('text'),
    letterSpacing: '-0.035em',
    lineHeight: 1.1,
  },
  canvasWorkflowHeaderStats: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
  },
  canvasWorkflowHeaderCount: {
    fontSize: 11,
    fontWeight: 700,
    color: cssVar('textSecondary'),
    background: cssVar('bgSurface'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: '999px',
    padding: '3px 8px',
    fontVariantNumeric: 'tabular-nums',
  },
  canvasWorkflowMessages: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '16px 14px 18px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 0,
  },
  canvasWorkflowNode: {
    display: 'grid',
    gridTemplateColumns: '30px minmax(0, 1fr)',
    gap: 8,
    animation: 'pg-fadein 0.25s ease-out',
  },
  canvasWorkflowNodeActive: {
    filter: 'drop-shadow(0 12px 24px rgba(45, 212, 191, 0.10))',
  },
  canvasWorkflowNodeRail: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    paddingTop: 8,
  },
  canvasWorkflowNodeIndex: {
    width: 26,
    height: 26,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    background: cssVar('bgSurface'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    color: cssVar('textSecondary'),
    fontFamily: cssVar('fontMono'),
    fontSize: 10,
    fontWeight: 800,
  },
  canvasWorkflowNodeLine: {
    width: 1,
    flex: 1,
    minHeight: 18,
    margin: '6px 0',
    background: `linear-gradient(180deg, ${cssVar('border')} 0%, transparent 100%)`,
  },
  canvasWorkflowNodeBody: {
    minWidth: 0,
    height: 310,
    marginBottom: 12,
    padding: 12,
    borderRadius: 18,
    border: `1px solid ${cssVar('borderSubtle')}`,
    background: `linear-gradient(145deg, ${cssVar('bgSurface')} 0%, ${cssVar('bg')} 100%)`,
    boxShadow: '0 14px 36px rgba(0, 0, 0, 0.12)',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
  },
  canvasWorkflowNodeContent: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 9,
    overflowY: 'auto' as const,
    overflowX: 'hidden' as const,
    overscrollBehavior: 'contain' as const,
    paddingRight: 2,
  },
  canvasWorkflowNodeTopline: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 9,
  },
  canvasWorkflowStatus: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '3px 8px',
    borderRadius: '999px',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.04em',
    fontFamily: cssVar('fontMono'),
  },
  canvasWorkflowStatusDone: {
    background: cssVar('bgDeep'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    color: cssVar('textTertiary'),
  },
  canvasWorkflowStatusLive: {
    background: cssVar('primarySubtle'),
    border: `1px solid ${cssVar('primary')}`,
    borderColor: 'rgba(45, 212, 191, 0.35)',
    color: cssVar('primary'),
  },
  canvasWorkflowStatusFailed: {
    background: cssVar('dangerSubtle'),
    border: `1px solid ${cssVar('danger')}`,
    borderColor: 'rgba(251, 113, 133, 0.35)',
    color: cssVar('danger'),
  },
  canvasWorkflowTime: {
    color: cssVar('textTertiary'),
    fontFamily: cssVar('fontMono'),
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
  },
  canvasWorkflowPrompt: {
    color: cssVar('text'),
    fontSize: 13,
    fontWeight: 650,
    lineHeight: 1.45,
    letterSpacing: '-0.006em',
    wordBreak: 'break-word' as const,
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical' as const,
    overflow: 'hidden',
    cursor: 'pointer',
    borderRadius: 6,
    transition: 'background 0.15s',
  },
  canvasPromptPopover: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    background: cssVar('bgSurface'),
    border: `1px solid ${cssVar('border')}`,
    borderRadius: 12,
    boxShadow: '0 12px 40px rgba(0, 0, 0, 0.35)',
    display: 'flex',
    flexDirection: 'column' as const,
    maxHeight: 220,
    animation: 'pg-fadein 0.15s ease-out',
  },
  canvasPromptPopoverHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 10px',
    borderBottom: `1px solid ${cssVar('borderSubtle')}`,
    flexShrink: 0,
  },
  canvasPromptPopoverTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: cssVar('textSecondary'),
    fontFamily: cssVar('fontMono'),
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  canvasPromptPopoverBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '3px 8px',
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: 6,
    background: cssVar('bgDeep'),
    color: cssVar('primary'),
    fontSize: 11,
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'background 0.15s, border-color 0.15s',
  },
  canvasPromptPopoverCloseBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 24,
    height: 24,
    padding: 0,
    border: 'none',
    borderRadius: 6,
    background: 'transparent',
    color: cssVar('textTertiary'),
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  canvasPromptPopoverBody: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto' as const,
    padding: '10px 12px',
    fontSize: 12.5,
    lineHeight: 1.6,
    color: cssVar('text'),
    wordBreak: 'break-word' as const,
    whiteSpace: 'pre-wrap' as const,
  },
  canvasNodeRegenBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '3px 8px',
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: '999px',
    background: cssVar('bgDeep'),
    color: cssVar('textSecondary'),
    fontSize: 10,
    fontWeight: 700,
    fontFamily: cssVar('fontMono'),
    cursor: 'pointer',
    transition: 'background 0.15s, color 0.15s, border-color 0.15s',
    whiteSpace: 'nowrap' as const,
  },
  canvasWorkflowImageGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 7,
  },
  canvasWorkflowImageButton: {
    display: 'block',
    width: '100%',
    aspectRatio: '1 / 1',
    padding: 0,
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: 11,
    background: cssVar('bgDeep'),
    overflow: 'hidden',
    cursor: 'zoom-in',
    boxShadow: 'inset 0 0 0 1px rgba(255, 255, 255, 0.03)',
  },
  canvasWorkflowImage: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
  },
  canvasWorkflowPendingSlot: {
    display: 'flex',
    alignItems: 'center',
    gap: 9,
    minHeight: 120,
    padding: '12px',
    borderRadius: 12,
    background: cssVar('primarySubtle'),
    border: `1px dashed ${cssVar('primary')}`,
    borderColor: 'rgba(45, 212, 191, 0.36)',
    color: cssVar('primary'),
    fontSize: 12,
    fontWeight: 700,
  },
  canvasWorkflowFailedSlot: {
    display: 'flex',
    alignItems: 'center',
    gap: 9,
    minHeight: 120,
    padding: '12px',
    borderRadius: 12,
    background: cssVar('dangerSubtle'),
    border: `1px dashed ${cssVar('danger')}`,
    borderColor: 'rgba(251, 113, 133, 0.36)',
    color: cssVar('danger'),
    fontSize: 12,
    fontWeight: 700,
  },
  canvasWorkflowText: {
    marginTop: 8,
    fontSize: 12,
    lineHeight: '1.5',
    color: cssVar('textSecondary'),
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical' as const,
    overflow: 'hidden',
  },
  canvasWorkflowNodeMeta: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 10,
    paddingTop: 9,
    borderTop: `1px solid ${cssVar('borderSubtle')}`,
    color: cssVar('textTertiary'),
    fontSize: 10,
    fontFamily: cssVar('fontMono'),
    flexShrink: 0,
  },
  canvasWorkflowMetaStack: {
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-start',
    gap: 5,
  },
  canvasWorkflowMetaStackEnd: {
    alignItems: 'flex-end',
    textAlign: 'right' as const,
  },
  canvasWorkflowModel: {
    display: 'inline-flex',
    alignSelf: 'flex-end',
    maxWidth: '100%',
    padding: '2px 6px',
    borderRadius: '999px',
    background: cssVar('bgDeep'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    fontSize: 10,
    fontFamily: cssVar('fontMono'),
    color: cssVar('textTertiary'),
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  canvasWorkflowOutputCount: {
    whiteSpace: 'nowrap' as const,
  },
  canvasWorkflowEmptyHint: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    minHeight: 260,
    padding: '44px 24px',
    color: cssVar('textTertiary'),
    fontSize: 13,
    lineHeight: 1.5,
    textAlign: 'center' as const,
    flex: 1,
  },
  canvasWorkflowEmptyOrb: {
    width: 70,
    height: 70,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    background: `linear-gradient(145deg, ${cssVar('primarySubtle')}, ${cssVar('bgSurface')})`,
    color: cssVar('primary'),
    border: `1px solid ${cssVar('borderSubtle')}`,
    boxShadow: '0 18px 42px rgba(0, 0, 0, 0.16)',
  },
  canvasWorkflowInput: {
    position: 'absolute' as const,
    left: '50%',
    bottom: 22,
    zIndex: 12,
    width: 'min(620px, calc(100% - 44px))',
    padding: 0,
    transform: 'translateX(-50%)',
    pointerEvents: 'auto' as const,
    flexShrink: 0,
  },
  canvasInputRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  canvasInputIconBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: 8,
    background: 'transparent',
    color: cssVar('textSecondary'),
    cursor: 'pointer',
    fontFamily: 'inherit',
    flexShrink: 0,
    transition: cssVar('transition'),
  },
  canvasInputSendBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    border: 'none',
    borderRadius: 8,
    background: cssVar('primary'),
    color: cssVar('primaryForeground'),
    cursor: 'pointer',
    fontFamily: 'inherit',
    flexShrink: 0,
    transition: cssVar('transition'),
  },
  canvasTaskIndicator: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: 10,
    padding: '18px 12px',
    borderRadius: 10,
    background: cssVar('bgSurface'),
    border: `1px solid ${cssVar('borderSubtle')}`,
  },
  canvasTaskSpinner: {
    width: 24,
    height: 24,
    border: `2.5px solid ${cssVar('borderSubtle')}`,
    borderTopColor: cssVar('primary'),
    borderRadius: '50%',
    animation: 'pg-spin 0.8s linear infinite',
  },
  canvasTaskLabel: {
    fontSize: 13,
    fontWeight: 500,
    color: cssVar('text'),
    textAlign: 'center' as const,
  },
  canvasTaskHint: {
    fontSize: 11,
    color: cssVar('textTertiary'),
    textAlign: 'center' as const,
  },
  canvasWorkflowStreaming: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    padding: '2px 0',
  },
  canvasWorkflowDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: cssVar('primary'),
    animation: 'pg-pulse 1.2s ease-in-out infinite',
  },
};
