import type { CSSProperties } from 'react';
import { cssVar } from '@doudou-start/airgate-theme';

export const workflowStyles: Record<string, CSSProperties> = {
  // Layout
  layout: {
    display: 'flex',
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    background: cssVar('bgDeep'),
    color: cssVar('text'),
    fontFamily: cssVar('fontSans'),
  },

  // Sidebar
  sidebar: {
    width: 260,
    minWidth: 260,
    display: 'flex',
    flexDirection: 'column' as const,
    background: cssVar('bg'),
    borderRight: `1px solid ${cssVar('borderSubtle')}`,
    overflow: 'hidden',
  },
  sidebarHeader: {
    padding: '16px 14px 12px',
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
    color: cssVar('textTertiary'),
    fontFamily: cssVar('fontMono') || 'monospace',
  },
  sidebarCategory: {
    padding: '8px 10px 4px',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.05em',
    textTransform: 'uppercase' as const,
    color: cssVar('textTertiary'),
  },
  sidebarNodeItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 14px',
    margin: '0 6px 2px',
    borderRadius: 8,
    cursor: 'grab',
    fontSize: 12,
    fontWeight: 500,
    color: cssVar('textSecondary'),
    transition: 'background 0.12s',
    border: 'none',
    background: 'transparent',
    width: 'calc(100% - 12px)',
    textAlign: 'left' as const,
    fontFamily: 'inherit',
  },
  sidebarNodeDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    flexShrink: 0,
  },
  sidebarDivider: {
    height: 1,
    margin: '8px 14px',
    background: cssVar('borderSubtle'),
  },

  // Workflow list
  workflowList: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '4px 6px',
  },
  workflowItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '8px 10px',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 12,
    color: cssVar('textSecondary'),
    transition: 'background 0.12s',
  },
  workflowItemActive: {
    background: cssVar('bgHover'),
    color: cssVar('text'),
    fontWeight: 500,
  },

  // Canvas area
  canvasArea: {
    flex: 1,
    position: 'relative' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    minWidth: 0,
    overflow: 'hidden',
  },

  // Toolbar
  toolbar: {
    position: 'absolute' as const,
    top: 12,
    right: 12,
    zIndex: 5,
    display: 'flex',
    gap: 4,
    padding: '4px 6px',
    borderRadius: 10,
    background: 'rgba(0, 0, 0, 0.55)',
    backdropFilter: 'blur(10px)',
  },
  toolbarBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    height: 32,
    padding: '0 12px',
    border: 'none',
    borderRadius: 7,
    background: 'transparent',
    color: '#fff',
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'background 0.12s',
    whiteSpace: 'nowrap' as const,
  },
  toolbarBtnPrimary: {
    background: cssVar('primary'),
    color: '#000',
  },

  // Node styles
  node: {
    width: 280,
    background: cssVar('bgElevated'),
    border: `1px solid ${cssVar('border')}`,
    borderRadius: 12,
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.2)',
    fontSize: 12,
  },
  nodeSelected: {
    borderColor: cssVar('primary'),
    boxShadow: `0 0 0 2px ${cssVar('primary')}40, 0 8px 24px rgba(0, 0, 0, 0.3)`,
  },
  nodeHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '8px 12px',
    fontWeight: 700,
    fontSize: 11,
    letterSpacing: '0.02em',
    color: '#fff',
    borderRadius: '12px 12px 0 0',
  },
  nodeHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
  },
  nodeHeaderLabel: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  nodePlayBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 24,
    height: 24,
    border: 'none',
    borderRadius: 6,
    background: 'rgba(255,255,255,0.15)',
    color: '#fff',
    cursor: 'pointer',
    flexShrink: 0,
    padding: 0,
    transition: 'background 0.12s',
  },
  nodeBody: {
    padding: '8px 0',
  },
  nodePortRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '4px 12px',
    fontSize: 11,
    color: cssVar('textSecondary'),
  },
  nodePortLabel: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  nodePortControl: {
    flex: 1,
    minWidth: 0,
  },
  nodeOutputRow: {
    justifyContent: 'flex-end',
    textAlign: 'right' as const,
  },
  nodeTextarea: {
    width: '100%',
    minHeight: 48,
    maxHeight: 120,
    padding: '6px 8px',
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: 6,
    background: cssVar('bgDeep'),
    color: cssVar('text'),
    fontSize: 11,
    fontFamily: 'inherit',
    resize: 'vertical' as const,
    outline: 'none',
  },
  nodeInput: {
    width: '100%',
    padding: '4px 8px',
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: 6,
    background: cssVar('bgDeep'),
    color: cssVar('text'),
    fontSize: 11,
    fontFamily: 'inherit',
    outline: 'none',
  },
  nodeSelect: {
    width: '100%',
    padding: '4px 8px',
    border: `1px solid ${cssVar('borderSubtle')}`,
    borderRadius: 6,
    background: cssVar('bgDeep'),
    color: cssVar('text'),
    fontSize: 11,
    fontFamily: 'inherit',
    outline: 'none',
    cursor: 'pointer',
    appearance: 'none' as const,
  },

  // Status
  nodeStatus: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 12px',
    fontSize: 10,
    fontWeight: 600,
    fontFamily: cssVar('fontMono') || 'monospace',
  },
  nodeStatusRunning: {
    color: cssVar('primary'),
  },
  nodeStatusCompleted: {
    color: '#4ade80',
  },
  nodeStatusError: {
    color: cssVar('danger'),
  },

  // Result preview
  nodePreview: {
    padding: '4px 12px 8px',
  },
  nodePreviewImage: {
    width: '100%',
    maxHeight: 160,
    objectFit: 'contain' as const,
    borderRadius: 6,
    background: cssVar('bgDeep'),
  },
  nodePreviewText: {
    padding: '6px 8px',
    borderRadius: 6,
    background: cssVar('bgDeep'),
    color: cssVar('textSecondary'),
    fontSize: 10,
    lineHeight: 1.5,
    maxHeight: 60,
    overflow: 'hidden',
    wordBreak: 'break-word' as const,
  },
  nodePreviewGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: 4,
  },

  // Port handle
  port: {
    width: 12,
    height: 12,
    borderRadius: '50%',
    border: '2px solid',
    background: cssVar('bgDeep'),
    cursor: 'crosshair',
  },
  portConnected: {
    background: 'currentColor',
  },

  // Footer / divider
  nodeDivider: {
    height: 1,
    margin: '0 12px',
    background: cssVar('borderSubtle'),
  },
  nodeFooter: {
    padding: '6px 12px 8px',
  },

  // Input area at bottom
  inputArea: {
    position: 'absolute' as const,
    bottom: 16,
    left: '50%',
    transform: 'translateX(-50%)',
    width: 'min(600px, calc(100% - 32px))',
    zIndex: 5,
    padding: '10px 14px',
    borderRadius: 14,
    background: cssVar('bgElevated'),
    border: `1px solid ${cssVar('border')}`,
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
    display: 'flex',
    alignItems: 'flex-end',
    gap: 8,
  },
  inputTextarea: {
    flex: 1,
    minHeight: 24,
    maxHeight: 120,
    padding: 0,
    border: 'none',
    background: 'transparent',
    color: cssVar('text'),
    fontSize: 13,
    fontFamily: 'inherit',
    resize: 'none' as const,
    outline: 'none',
    lineHeight: 1.5,
  },
  inputSendBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    border: 'none',
    borderRadius: 8,
    background: cssVar('primary'),
    color: '#000',
    cursor: 'pointer',
    flexShrink: 0,
    padding: 0,
    transition: 'opacity 0.12s',
  },
};
